#!/bin/bash

if [ $# -lt 2 ] ; then
	echo "Usage: megs command [args]..."
	exit 1
fi

memory="$1"
shift

case "$memory" in 
	*M|*m)
		memory=$( expr substr "$memory" 1 '(' "$memory" : '[0-9]*' ')' '*' 1024 )
	;;

	*K|*k)
		memory=$( expr substr "$memory" 1 '(' "$memory" : '[0-9]*' ')' )
	;;

	*)
		echo "Specify units in M or K"
		exit 1;
	;;
	
esac

# Set the memory limit for the process
ulimit -m "$memory" -v "$memory"

# Execute the command
exec "$@"
