#!/usr/bin/perl

use strict;
use warnings;

use Cwd qw(abs_path getcwd);
use File::Spec;
use Getopt::Long;

sub main {

	die "Usage: server args...\n" unless @ARGV >= 2;
	my ($server, @args) = @ARGV;

    my $dir = abs_path(getcwd());
    my $home = abs_path("$ENV{HOME}");
    
	my $regexp_root;
    my $path;
	{
        my $quoted = quotemeta($home);
		my $regexp = qr/^ $quoted /x;
        if ($dir !~ m,$regexp / (.*) ,x) {
            die "Folder $dir is not in $home";
        }
        $path = $1;
	}

    my $dest_root = "$server:$path";
	my @command = ('rsync', '--relative', '-CcrlDv', @args, $dest_root);
	print "@command\n";

	my $exit = system(@command);
	if ($exit != 0) {
		warn "Failed to execute @command; $!";
	}
	return $exit >> 8;
}


exit main() unless caller;
