#!/bin/bash

# Configure the dual display
set-monitors

# Disable the touch pad
toggle-touchpad

# Disable the proxy
gsettings set org.gnome.system.proxy autoconfig-url ""

# Set the keyboar mapping that I want
xmodmap ~/.Xmodmap

# Fix the panel
#~/Projects/gir-fun/wnck-fix-panel.pl


###
# Fix compiz settings

# Shortcut to nedit
gsettings set org.compiz.integrated command-1 nedit
gsettings set org.compiz.integrated run-command-1 "['<Super>n']"

# Shortcut to hierarchyviewer
gsettings set org.compiz.integrated command-2 /home/erodriguez/android/tools/hierarchyviewer
gsettings set org.compiz.integrated run-command-2 "['<Super>h']"

# Shortcut to gedit
gsettings set org.compiz.integrated command-3 gedit
gsettings set org.compiz.integrated run-command-3 "['<Super>g']"

# Shortcut to thunderbird
gsettings set org.compiz.integrated command-4 thunderbird
gsettings set org.compiz.integrated run-command-4 "['<Super>m']"

# Toggle touchpad
gsettings set org.compiz.integrated command-5 /home/erodriguez/bin/toggle-touchpad
gsettings set org.compiz.integrated run-command-5 "['<Super>t']"

# Screenshot
gsettings set org.compiz.integrated command-6 'gnome-screenshot --interactive'
gsettings set org.compiz.integrated run-command-6 "['<Super><Alt>p']"

# Lock screen
gsettings set org.compiz.integrated command-7 'gnome-screensaver-command -l'
gsettings set org.compiz.integrated run-command-7 "['<Super>l']"

# Terminal
gsettings set org.compiz.integrated command-8 gnome-terminal
gsettings set org.compiz.integrated run-command-8 "['<Super>slash']"

# Calculator
gsettings set org.compiz.integrated command-8 gnome-calculator
gsettings set org.compiz.integrated run-command-8 "['<Super>c']"


# Workspace shortcuts
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left  "['<Super>Left']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "['<Super>Right']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up    "['<Super>Up']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down  "['<Super>Down']"

gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-left  "['<Control><Super>Left']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-right "['<Control><Super>Right']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-up    "['<Control><Super>Up']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-down  "['<Control><Super>Down']"


# Set the proper plugin order. Make expo the last so that it doens't lose it's key bindings
#dconf write /org/compiz/profiles/Default/plugins/core/active-plugins "['core', 'composite', 'opengl', 'decor', 'compiztoolbox', 'shift', 'commands', 'mousepoll', 'snap', 'regex', 'titleinfo', 'imgpng', 'wall', 'place', 'session', 'resize', 'move', 'animation', 'workarounds', 'fade', 'scale', 'expo']"
