#!/bin/bash

# Configure the dual display
set-monitors

# Disable the proxy
gsettings set org.gnome.system.proxy autoconfig-url ""

# Set the keyboar mapping that I want
xmodmap ~/.Xmodmap

# Fix the panel
~/Projects/gir-fun/wnck-fix-panel.pl


###
# Fix compiz settings

# Shortcut to nedit
gsettings set org.compiz.integrated command-1 nedit
gsettings set org.compiz.integrated run-command-1 "['<Super>n']"

# Shortcut to hierarchyviewer
gsettings set org.compiz.integrated command-2 /home/erodriguez/android/tools/hierarchyviewer
gsettings set org.compiz.integrated run-command-2 "['<Super>h']"

# Shortcut to gedit
gsettings set org.compiz.integrated command-3 gedit
gsettings set org.compiz.integrated run-command-3 "['<Super>g']"

# Shortcut to thunderbird
gsettings set org.compiz.integrated command-4 thunderbird
gsettings set org.compiz.integrated run-command-4 "['<Super>m']"

# Toggle touchpad
gsettings set org.compiz.integrated command-5 /home/erodriguez/bin/toggle-touchpad
gsettings set org.compiz.integrated run-command-5 "['<Super>t']"


# Workspace shortcuts
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left  "['<Super>Left']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "['<Super>Right']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up    "['<Super>Up']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down  "['<Super>Down']"

gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-left  "['<Control><Super>Left']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-right "['<Control><Super>Right']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-up    "['<Control><Super>Up']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-down  "['<Control><Super>Down']"
